import { NextResponse, type NextRequest } from 'next/server';
import { SESSION_COOKIE_NAME } from '@/lib/auth/sessions';

const PUBLIC_PATHS = ['/', '/login', '/api/auth/login', '/api/health'];

// Metadata image routes generated by Next.js from app/(icon|apple-icon|opengraph-image|twitter-image).tsx.
// They serve PNGs for social cards and favicons and must be reachable without auth.
const PUBLIC_PATH_PREFIXES = [
  '/_next',
  '/icon',
  '/apple-icon',
  '/opengraph-image',
  '/twitter-image',
];

export function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl;

  if (
    PUBLIC_PATHS.some((p) => pathname === p) ||
    PUBLIC_PATH_PREFIXES.some((p) => pathname === p || pathname.startsWith(`${p}/`) || pathname.startsWith(`${p}.`)) ||
    pathname === '/favicon.ico'
  ) {
    return NextResponse.next();
  }

  const hasSession = Boolean(req.cookies.get(SESSION_COOKIE_NAME)?.value);

  if (!hasSession) {
    if (pathname.startsWith('/api/')) {
      return NextResponse.json({ error: 'unauthenticated' }, { status: 401 });
    }
    const url = req.nextUrl.clone();
    url.pathname = '/login';
    url.searchParams.set('next', pathname);
    return NextResponse.redirect(url);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
